<?php
/**
 * Nedir.me Kavram Import Script
 * Bu script tüm kavramları WordPress'e ekler
 * Kullanım: WordPress admin'de çalıştırın veya mu-plugins'e ekleyin
 */

// Prevent direct access
if (!defined('ABSPATH')) {
    exit;
}

// Run once on admin init
add_action('admin_init', 'nedir_import_kavramlar_once');

function nedir_import_kavramlar_once() {
    // Check if already imported
    if (get_option('nedir_kavramlar_imported')) {
        return;
    }
    
    // Only run for admin users
    if (!current_user_can('manage_options')) {
        return;
    }
    
    // Check for import trigger
    if (!isset($_GET['import_kavramlar'])) {
        return;
    }
    
    nedir_import_all_kavramlar();
    update_option('nedir_kavramlar_imported', true);
    
    wp_die('Import tamamlandı! 1000 kavram eklendi. <a href="' . admin_url('edit.php?post_type=kavram') . '">Kavramları Gör</a>');
}

function nedir_import_all_kavramlar() {
    // Kategorileri oluştur
    $categories = array(
        'insan-zihin' => array(
            'name' => 'İnsan & Zihin',
            'icon' => '🧠',
            'description' => 'Psikoloji, duygular, zihinsel süreçler ve insan davranışları'
        ),
        'dijital-teknoloji' => array(
            'name' => 'Dijital & Teknoloji',
            'icon' => '💻',
            'description' => 'İnternet, yazılım, donanım ve dijital dünya'
        ),
        'ekonomi' => array(
            'name' => 'Ekonomi & Finans',
            'icon' => '💰',
            'description' => 'Para, piyasalar, yatırım ve finansal kavramlar'
        ),
        'hukuk' => array(
            'name' => 'Hukuk',
            'icon' => '⚖️',
            'description' => 'Yasal süreçler, haklar ve hukuki kavramlar'
        ),
        'saglik' => array(
            'name' => 'Sağlık & Beden',
            'icon' => '🩺',
            'description' => 'Tıp, beden fonksiyonları ve sağlık kavramları'
        ),
        'egitim' => array(
            'name' => 'Eğitim',
            'icon' => '🎓',
            'description' => 'Okul, öğrenme ve akademik kavramlar'
        ),
        'sosyal' => array(
            'name' => 'Sosyal & Günlük',
            'icon' => '🌍',
            'description' => 'Toplumsal kavramlar ve sosyal yaşam'
        ),
        'genel' => array(
            'name' => 'Genel Kavramlar',
            'icon' => '🧩',
            'description' => 'Soyut ve genel kavramlar'
        ),
    );
    
    // Create taxonomy terms
    foreach ($categories as $slug => $cat) {
        if (!term_exists($slug, 'ana-kategori')) {
            wp_insert_term($cat['name'], 'ana-kategori', array(
                'slug' => $slug,
                'description' => $cat['icon'] . ' ' . $cat['description'],
            ));
        }
    }
    
    // Tüm kavramlar
    $kavramlar = array(
        // 🧠 İnsan & Zihin (1-80)
        array('Stres', 'insan-zihin'),
        array('Kaygı', 'insan-zihin'),
        array('Anksiyete', 'insan-zihin'),
        array('Panik atak', 'insan-zihin'),
        array('Depresyon', 'insan-zihin'),
        array('Tükenmişlik', 'insan-zihin'),
        array('Motivasyon', 'insan-zihin'),
        array('Odak', 'insan-zihin'),
        array('Dikkat', 'insan-zihin'),
        array('Konsantrasyon', 'insan-zihin'),
        array('Alışkanlık', 'insan-zihin'),
        array('Erteleme', 'insan-zihin'),
        array('Özgüven', 'insan-zihin'),
        array('Özsaygı', 'insan-zihin'),
        array('Özşefkat', 'insan-zihin'),
        array('Yalnızlık', 'insan-zihin'),
        array('Kıskançlık', 'insan-zihin'),
        array('Utanç', 'insan-zihin'),
        array('Suçluluk', 'insan-zihin'),
        array('Sabır', 'insan-zihin'),
        array('Öfke', 'insan-zihin'),
        array('Stres hormonu', 'insan-zihin'),
        array('Travma', 'insan-zihin'),
        array('Fobi', 'insan-zihin'),
        array('Bağımlılık', 'insan-zihin'),
        array('Takıntı', 'insan-zihin'),
        array('Obsesyon', 'insan-zihin'),
        array('Bilinç', 'insan-zihin'),
        array('Bilinçaltı', 'insan-zihin'),
        array('Algı', 'insan-zihin'),
        array('Zihin', 'insan-zihin'),
        array('Farkındalık', 'insan-zihin'),
        array('Empati', 'insan-zihin'),
        array('Sempati', 'insan-zihin'),
        array('İrade', 'insan-zihin'),
        array('Karar verme', 'insan-zihin'),
        array('İç motivasyon', 'insan-zihin'),
        array('Dış motivasyon', 'insan-zihin'),
        array('Hedef', 'insan-zihin'),
        array('Niyet', 'insan-zihin'),
        array('Duygu', 'insan-zihin'),
        array('His', 'insan-zihin'),
        array('Mutluluk', 'insan-zihin'),
        array('Tatmin', 'insan-zihin'),
        array('Memnuniyet', 'insan-zihin'),
        array('Hayal kırıklığı', 'insan-zihin'),
        array('Umut', 'insan-zihin'),
        array('Umutsuzluk', 'insan-zihin'),
        array('Değer', 'insan-zihin'),
        array('İnanç', 'insan-zihin'),
        array('Düşünce', 'insan-zihin'),
        array('Düşünce kalıbı', 'insan-zihin'),
        array('Zihinsel yorgunluk', 'insan-zihin'),
        array('Beyin sisi', 'insan-zihin'),
        array('Zihinsel blokaj', 'insan-zihin'),
        array('Özgürlük hissi', 'insan-zihin'),
        array('Kontrol ihtiyacı', 'insan-zihin'),
        array('Kaçınma davranışı', 'insan-zihin'),
        array('Aşırı düşünme', 'insan-zihin'),
        array('Ruminasyon', 'insan-zihin'),
        array('Negatif iç ses', 'insan-zihin'),
        array('İç diyalog', 'insan-zihin'),
        array('Kendilik algısı', 'insan-zihin'),
        array('Benlik', 'insan-zihin'),
        array('Kimlik', 'insan-zihin'),
        array('Kişilik', 'insan-zihin'),
        array('Karakter', 'insan-zihin'),
        array('Tutum', 'insan-zihin'),
        array('Davranış', 'insan-zihin'),
        array('Tepki', 'insan-zihin'),
        array('Alışkanlık döngüsü', 'insan-zihin'),
        array('Otomatik düşünce', 'insan-zihin'),
        array('Bilişsel çarpıtma', 'insan-zihin'),
        array('Felaketleştirme', 'insan-zihin'),
        array('Siyah beyaz düşünme', 'insan-zihin'),
        array('Onay ihtiyacı', 'insan-zihin'),
        array('Yetersizlik hissi', 'insan-zihin'),
        array('Sosyal kaygı', 'insan-zihin'),
        array('Performans kaygısı', 'insan-zihin'),
        array('İç huzur', 'insan-zihin'),
        
        // 💻 Dijital & İnternet (81-150)
        array('Algoritma', 'dijital-teknoloji'),
        array('Yapay zeka', 'dijital-teknoloji'),
        array('Veri', 'dijital-teknoloji'),
        array('Dijital ayak izi', 'dijital-teknoloji'),
        array('Çerez (cookie)', 'dijital-teknoloji'),
        array('Bulut bilişim', 'dijital-teknoloji'),
        array('API', 'dijital-teknoloji'),
        array('Sunucu', 'dijital-teknoloji'),
        array('Tarayıcı', 'dijital-teknoloji'),
        array('Arama motoru', 'dijital-teknoloji'),
        array('SEO', 'dijital-teknoloji'),
        array('Backlink', 'dijital-teknoloji'),
        array('IP adresi', 'dijital-teknoloji'),
        array('VPN', 'dijital-teknoloji'),
        array('Firewall', 'dijital-teknoloji'),
        array('Spam', 'dijital-teknoloji'),
        array('Bot', 'dijital-teknoloji'),
        array('Troll', 'dijital-teknoloji'),
        array('Hashtag', 'dijital-teknoloji'),
        array('Influencer', 'dijital-teknoloji'),
        array('Viral içerik', 'dijital-teknoloji'),
        array('Deep web', 'dijital-teknoloji'),
        array('Dark web', 'dijital-teknoloji'),
        array('Blockchain', 'dijital-teknoloji'),
        array('NFT', 'dijital-teknoloji'),
        array('Kripto para', 'dijital-teknoloji'),
        array('Dijital cüzdan', 'dijital-teknoloji'),
        array('Akıllı sözleşme', 'dijital-teknoloji'),
        array('Metaverse', 'dijital-teknoloji'),
        array('Avatar', 'dijital-teknoloji'),
        array('Bulut depolama', 'dijital-teknoloji'),
        array('Dosya uzantısı', 'dijital-teknoloji'),
        array('PDF', 'dijital-teknoloji'),
        array('Cache', 'dijital-teknoloji'),
        array('Çöp veri', 'dijital-teknoloji'),
        array('Veri ihlali', 'dijital-teknoloji'),
        array('Siber güvenlik', 'dijital-teknoloji'),
        array('Şifreleme', 'dijital-teknoloji'),
        array('İki adımlı doğrulama', 'dijital-teknoloji'),
        array('Phishing', 'dijital-teknoloji'),
        array('Kötü amaçlı yazılım', 'dijital-teknoloji'),
        array('Virüs yazılımı', 'dijital-teknoloji'),
        array('Güncelleme', 'dijital-teknoloji'),
        array('Patch', 'dijital-teknoloji'),
        array('Açık kaynak', 'dijital-teknoloji'),
        array('Lisans', 'dijital-teknoloji'),
        array('Domain', 'dijital-teknoloji'),
        array('Hosting', 'dijital-teknoloji'),
        array('HTTP', 'dijital-teknoloji'),
        array('HTTPS', 'dijital-teknoloji'),
        array('URL', 'dijital-teknoloji'),
        array('QR kod', 'dijital-teknoloji'),
        array('Mobil veri', 'dijital-teknoloji'),
        array('Wi-Fi', 'dijital-teknoloji'),
        array('Bluetooth', 'dijital-teknoloji'),
        array('E-posta', 'dijital-teknoloji'),
        array('Spam klasörü', 'dijital-teknoloji'),
        array('Push bildirimi', 'dijital-teknoloji'),
        array('Dijital bağımlılık', 'dijital-teknoloji'),
        array('Bildirim yorgunluğu', 'dijital-teknoloji'),
        array('Ekran süresi', 'dijital-teknoloji'),
        array('Algoritmik filtre', 'dijital-teknoloji'),
        array('Veri madenciliği', 'dijital-teknoloji'),
        array('Dijital mahremiyet', 'dijital-teknoloji'),
        array('Siber zorbalık', 'dijital-teknoloji'),
        array('Bulut yedekleme', 'dijital-teknoloji'),
        array('Yapay sinir ağı', 'dijital-teknoloji'),
        array('Makine öğrenmesi', 'dijital-teknoloji'),
        array('Büyük veri', 'dijital-teknoloji'),
        array('Dijital kimlik', 'dijital-teknoloji'),
        
        // 💰 Ekonomi (151-220)
        array('Enflasyon', 'ekonomi'),
        array('Faiz', 'ekonomi'),
        array('Arz', 'ekonomi'),
        array('Talep', 'ekonomi'),
        array('Piyasa', 'ekonomi'),
        array('Borsa', 'ekonomi'),
        array('Hisse senedi', 'ekonomi'),
        array('Endeks', 'ekonomi'),
        array('Likidite', 'ekonomi'),
        array('Resesyon', 'ekonomi'),
        array('Durgunluk', 'ekonomi'),
        array('Devalüasyon', 'ekonomi'),
        array('Revalüasyon', 'ekonomi'),
        array('Döviz kuru', 'ekonomi'),
        array('Kriz', 'ekonomi'),
        array('Gayrisafi yurt içi hasıla (GSYİH)', 'ekonomi'),
        array('İstihdam', 'ekonomi'),
        array('İşsizlik', 'ekonomi'),
        array('Asgari ücret', 'ekonomi'),
        array('Maaş bordrosu', 'ekonomi'),
        array('Zam', 'ekonomi'),
        array('Vergi', 'ekonomi'),
        array('Gelir vergisi', 'ekonomi'),
        array('Katma değer vergisi (KDV)', 'ekonomi'),
        array('ÖTV', 'ekonomi'),
        array('Bütçe', 'ekonomi'),
        array('Kamu harcaması', 'ekonomi'),
        array('Borç', 'ekonomi'),
        array('Kredi', 'ekonomi'),
        array('Faiz oranı', 'ekonomi'),
        array('Merkez bankası', 'ekonomi'),
        array('Para politikası', 'ekonomi'),
        array('Maliye politikası', 'ekonomi'),
        array('Enflasyon farkı', 'ekonomi'),
        array('Alım gücü', 'ekonomi'),
        array('Tüketici güveni', 'ekonomi'),
        array('Yatırım', 'ekonomi'),
        array('Tasarruf', 'ekonomi'),
        array('Birikim', 'ekonomi'),
        array('Ekonomik büyüme', 'ekonomi'),
        array('Cari açık', 'ekonomi'),
        array('Dış ticaret', 'ekonomi'),
        array('İhracat', 'ekonomi'),
        array('İthalat', 'ekonomi'),
        array('Kur farkı', 'ekonomi'),
        array('Nominal değer', 'ekonomi'),
        array('Reel değer', 'ekonomi'),
        array('Finansal okuryazarlık', 'ekonomi'),
        array('Risk', 'ekonomi'),
        array('Getiri', 'ekonomi'),
        array('Portföy', 'ekonomi'),
        array('Piyasa değeri', 'ekonomi'),
        array('Sermaye', 'ekonomi'),
        array('Temettü', 'ekonomi'),
        array('Bankacılık', 'ekonomi'),
        array('Dijital bankacılık', 'ekonomi'),
        array('Kredi notu', 'ekonomi'),
        array('Finansal istikrar', 'ekonomi'),
        array('Sigorta', 'ekonomi'),
        array('Prim', 'ekonomi'),
        array('Emeklilik', 'ekonomi'),
        array('BES', 'ekonomi'),
        array('Tazminat', 'ekonomi'),
        array('Kira', 'ekonomi'),
        array('Konut kredisi', 'ekonomi'),
        array('Faiz indirimi', 'ekonomi'),
        array('Faiz artışı', 'ekonomi'),
        array('Alacak', 'ekonomi'),
        array('Borçlu', 'ekonomi'),
        array('Alacaklı', 'ekonomi'),
        
        // ⚖️ Hukuk (221-270)
        array('Hukuk', 'hukuk'),
        array('Hak', 'hukuk'),
        array('Yükümlülük', 'hukuk'),
        array('Sorumluluk', 'hukuk'),
        array('Suç', 'hukuk'),
        array('Ceza', 'hukuk'),
        array('Dava', 'hukuk'),
        array('Mahkeme', 'hukuk'),
        array('Savcı', 'hukuk'),
        array('Hâkim', 'hukuk'),
        array('Avukat', 'hukuk'),
        array('İcra', 'hukuk'),
        array('Haciz', 'hukuk'),
        array('Tazminat (hukuk)', 'hukuk'),
        array('Sözleşme', 'hukuk'),
        array('İmza', 'hukuk'),
        array('Tebligat', 'hukuk'),
        array('İtiraz', 'hukuk'),
        array('Şikâyet', 'hukuk'),
        array('Uzlaşma', 'hukuk'),
        array('Arabuluculuk', 'hukuk'),
        array('Yargılama', 'hukuk'),
        array('Karar', 'hukuk'),
        array('Hüküm', 'hukuk'),
        array('Delil', 'hukuk'),
        array('Tanık', 'hukuk'),
        array('Sanık', 'hukuk'),
        array('Mağdur', 'hukuk'),
        array('Müşteki', 'hukuk'),
        array('Zamanaşımı', 'hukuk'),
        array('Dilekçe', 'hukuk'),
        array('Dosya numarası', 'hukuk'),
        array('Tutanak', 'hukuk'),
        array('Noter', 'hukuk'),
        array('Resmi belge', 'hukuk'),
        array('Kimlik (hukuk)', 'hukuk'),
        array('Vekâlet', 'hukuk'),
        array('Miras', 'hukuk'),
        array('Vasiyet', 'hukuk'),
        array('Nafaka', 'hukuk'),
        array('Boşanma', 'hukuk'),
        array('Mal paylaşımı', 'hukuk'),
        array('İcra takibi', 'hukuk'),
        array('İflas', 'hukuk'),
        array('Konkordato', 'hukuk'),
        array('Cezaevi', 'hukuk'),
        array('Hükümlü', 'hukuk'),
        array('Tutuklu', 'hukuk'),
        array('Adli sicil', 'hukuk'),
        array('Sabıka kaydı', 'hukuk'),
        
        // 🩺 Sağlık (271-330)
        array('Bağışıklık', 'saglik'),
        array('Vitamin', 'saglik'),
        array('Mineral', 'saglik'),
        array('Hormon', 'saglik'),
        array('Metabolizma', 'saglik'),
        array('Diyabet', 'saglik'),
        array('Tansiyon', 'saglik'),
        array('Kolesterol', 'saglik'),
        array('Alerji', 'saglik'),
        array('Virüs', 'saglik'),
        array('Bakteri', 'saglik'),
        array('Enfeksiyon', 'saglik'),
        array('Antibiyotik', 'saglik'),
        array('Aşı', 'saglik'),
        array('Bağışıklık sistemi', 'saglik'),
        array('Kalori', 'saglik'),
        array('Vücut kitle indeksi', 'saglik'),
        array('Nabız', 'saglik'),
        array('Ateş', 'saglik'),
        array('Kan şekeri', 'saglik'),
        array('Anemi', 'saglik'),
        array('Kansızlık', 'saglik'),
        array('Tiroid', 'saglik'),
        array('Kortizol', 'saglik'),
        array('Serotonin', 'saglik'),
        array('Dopamin', 'saglik'),
        array('Melatonin', 'saglik'),
        array('Uyku', 'saglik'),
        array('REM uykusu', 'saglik'),
        array('Biyolojik saat', 'saglik'),
        array('Dehidrasyon', 'saglik'),
        array('Su kaybı', 'saglik'),
        array('Obezite', 'saglik'),
        array('Vücut yağı', 'saglik'),
        array('Sindirim', 'saglik'),
        array('Bağırsak', 'saglik'),
        array('Mikrobiyota', 'saglik'),
        array('Probiyotik', 'saglik'),
        array('Prebiyotik', 'saglik'),
        array('Enzim', 'saglik'),
        array('Karaciğer', 'saglik'),
        array('Böbrek', 'saglik'),
        array('Akciğer', 'saglik'),
        array('Kalp', 'saglik'),
        array('Damar', 'saglik'),
        array('Solunum', 'saglik'),
        array('Nefes', 'saglik'),
        array('Oksijen', 'saglik'),
        array('Karbondioksit', 'saglik'),
        array('İnsülin', 'saglik'),
        array('Glikoz', 'saglik'),
        array('Laktik asit', 'saglik'),
        array('Bağ dokusu', 'saglik'),
        array('Kemik', 'saglik'),
        array('Kas', 'saglik'),
        array('Sinir sistemi', 'saglik'),
        array('Beyin', 'saglik'),
        array('Omurilik', 'saglik'),
        array('Refleks', 'saglik'),
        array('Bağ dokusu iltihabı', 'saglik'),
        
        // 🎓 Eğitim (331-370)
        array('Eğitim', 'egitim'),
        array('Öğrenme', 'egitim'),
        array('Okul', 'egitim'),
        array('Sınıf', 'egitim'),
        array('Ders', 'egitim'),
        array('Müfredat', 'egitim'),
        array('Öğrenci', 'egitim'),
        array('Öğretmen', 'egitim'),
        array('Karne', 'egitim'),
        array('Diploma', 'egitim'),
        array('Rehberlik', 'egitim'),
        array('Sınav', 'egitim'),
        array('Yazılı', 'egitim'),
        array('Sözlü', 'egitim'),
        array('Not sistemi', 'egitim'),
        array('Devamsızlık', 'egitim'),
        array('Başarı', 'egitim'),
        array('Başarısızlık', 'egitim'),
        array('LGS', 'egitim'),
        array('YKS', 'egitim'),
        array('KPSS', 'egitim'),
        array('Ödev', 'egitim'),
        array('Proje ödevi', 'egitim'),
        array('Sunum', 'egitim'),
        array('Ders programı', 'egitim'),
        array('Seçmeli ders', 'egitim'),
        array('Zorunlu ders', 'egitim'),
        array('Akademik yıl', 'egitim'),
        array('Mezuniyet', 'egitim'),
        array('Okul yönetimi', 'egitim'),
        array('Kayıt', 'egitim'),
        array('Nakil', 'egitim'),
        array('Sınıf geçme', 'egitim'),
        array('Sınıfta kalma', 'egitim'),
        array('Telafi', 'egitim'),
        array('Okul kuralları', 'egitim'),
        array('Disiplin', 'egitim'),
        array('Belge', 'egitim'),
        array('Takdir belgesi', 'egitim'),
        array('Teşekkür belgesi', 'egitim'),
        
        // 🌐 Sosyal & İnternet Dili (371-400)
        array('DM', 'sosyal'),
        array('Story', 'sosyal'),
        array('Reels', 'sosyal'),
        array('Like', 'sosyal'),
        array('Yorum', 'sosyal'),
        array('Paylaşım', 'sosyal'),
        array('Hashtag kullanımı', 'sosyal'),
        array('Trend', 'sosyal'),
        array('Keşfet', 'sosyal'),
        array('Takipçi', 'sosyal'),
        array('Engelleme', 'sosyal'),
        array('Ban', 'sosyal'),
        array('Raporlama', 'sosyal'),
        array('Spam hesap', 'sosyal'),
        array('Fake hesap', 'sosyal'),
        array('Bio', 'sosyal'),
        array('Profil', 'sosyal'),
        array('Etkileşim', 'sosyal'),
        array('Algoritmik akış', 'sosyal'),
        array('Bildirim', 'sosyal'),
        array('Çevrim içi', 'sosyal'),
        array('Çevrim dışı', 'sosyal'),
        array('Avatar resmi', 'sosyal'),
        array('Kullanıcı adı', 'sosyal'),
        array('Gizli hesap', 'sosyal'),
        array('Açık hesap', 'sosyal'),
        array('Paylaşım ayarları', 'sosyal'),
        array('Hikâye gizleme', 'sosyal'),
        array('Sessize alma', 'sosyal'),
        array('Çıkış yapma', 'sosyal'),
    );
    
    // Part 2 kavramlar (401-600) - continuing
    $kavramlar_part2 = array(
        // 🧠 İnsan & Zihin (401-480)
        array('İçsel motivasyon', 'insan-zihin'),
        array('Dışsal motivasyon', 'insan-zihin'),
        array('Öz disiplin', 'insan-zihin'),
        array('İrade gücü', 'insan-zihin'),
        array('Kararlılık', 'insan-zihin'),
        array('Azim', 'insan-zihin'),
        array('Sabit fikir', 'insan-zihin'),
        array('Esneklik', 'insan-zihin'),
        array('Psikolojik dayanıklılık', 'insan-zihin'),
        array('Ruh hali', 'insan-zihin'),
        array('Duygusal dalgalanma', 'insan-zihin'),
        array('Duygusal tükenme', 'insan-zihin'),
        array('Duygusal boşluk', 'insan-zihin'),
        array('Ait olma ihtiyacı', 'insan-zihin'),
        array('Kabul görme ihtiyacı', 'insan-zihin'),
        array('Değer görme ihtiyacı', 'insan-zihin'),
        array('Anlam arayışı', 'insan-zihin'),
        array('Varoluşsal kaygı', 'insan-zihin'),
        array('Kimlik krizi', 'insan-zihin'),
        array('Rol karmaşası', 'insan-zihin'),
        array('Sosyal izolasyon', 'insan-zihin'),
        array('Sosyal bağ', 'insan-zihin'),
        array('Güven ihtiyacı', 'insan-zihin'),
        array('Kontrol duygusu', 'insan-zihin'),
        array('Kayıp korkusu', 'insan-zihin'),
        array('Başarısızlık korkusu', 'insan-zihin'),
        array('Onay arayışı', 'insan-zihin'),
        array('Yetersizlik algısı', 'insan-zihin'),
        array('Utanç duygusu', 'insan-zihin'),
        array('Suçluluk duygusu', 'insan-zihin'),
        array('Hayal kırıklığı eşiği', 'insan-zihin'),
        array('Umut seviyesi', 'insan-zihin'),
        array('Psikolojik sınır', 'insan-zihin'),
        array('Kişisel alan', 'insan-zihin'),
        array('Mental yük', 'insan-zihin'),
        array('Zihinsel esneklik', 'insan-zihin'),
        array('Zihinsel direnç', 'insan-zihin'),
        array('Zihinsel dayanıklılık', 'insan-zihin'),
        array('İç denge', 'insan-zihin'),
        array('Ruhsal denge', 'insan-zihin'),
        array('İç huzur hali', 'insan-zihin'),
        array('Duygusal farkındalık', 'insan-zihin'),
        array('Öz farkındalık', 'insan-zihin'),
        array('Kendini kabul', 'insan-zihin'),
        array('Kendini suçlama', 'insan-zihin'),
        array('Kendini sabote etme', 'insan-zihin'),
        array('Negatif düşünce döngüsü', 'insan-zihin'),
        array('Aşırı genelleme', 'insan-zihin'),
        array('Etiketleme (bilişsel)', 'insan-zihin'),
        array('Zihin okuma', 'insan-zihin'),
        array('Felaket senaryosu', 'insan-zihin'),
        array('Olumsuz filtre', 'insan-zihin'),
        array('Kutuplaşmış düşünme', 'insan-zihin'),
        array('Kişisel alma', 'insan-zihin'),
        array('Seçici algı', 'insan-zihin'),
        array('Kendilik değeri', 'insan-zihin'),
        array('Benlik saygısı', 'insan-zihin'),
        array('Kırılganlık', 'insan-zihin'),
        array('İçsel güven', 'insan-zihin'),
        array('Psikolojik esneklik', 'insan-zihin'),
        array('Duygusal regülasyon', 'insan-zihin'),
        array('Öz kontrol', 'insan-zihin'),
        array('İçsel denge', 'insan-zihin'),
        array('İçsel huzur', 'insan-zihin'),
        array('Ruhsal istikrar', 'insan-zihin'),
        array('Duygusal bağlanma', 'insan-zihin'),
        array('Güvenli bağlanma', 'insan-zihin'),
        array('Kaygılı bağlanma', 'insan-zihin'),
        array('Kaçıngan bağlanma', 'insan-zihin'),
        array('Travma tepkisi', 'insan-zihin'),
        array('Psikolojik tetikleyici', 'insan-zihin'),
        array('Duygusal tetiklenme', 'insan-zihin'),
        array('Psikolojik yük', 'insan-zihin'),
        array('Zihinsel yıpranma', 'insan-zihin'),
        array('Ruhsal yorgunluk', 'insan-zihin'),
        array('Mental blokaj', 'insan-zihin'),
        array('İçsel karmaşa', 'insan-zihin'),
        array('Psikolojik çöküş', 'insan-zihin'),
        array('Ruhsal kırılma', 'insan-zihin'),
        array('İçsel toparlanma', 'insan-zihin'),
        
        // 💻 Teknoloji & Dijital (481-550)
        array('Dijital okuryazarlık', 'dijital-teknoloji'),
        array('Veri güvenliği', 'dijital-teknoloji'),
        array('Sunucu yükü', 'dijital-teknoloji'),
        array('Bant genişliği', 'dijital-teknoloji'),
        array('Ping', 'dijital-teknoloji'),
        array('Gecikme süresi', 'dijital-teknoloji'),
        array('Paket kaybı', 'dijital-teknoloji'),
        array('Yük dengeleme', 'dijital-teknoloji'),
        array('CDN', 'dijital-teknoloji'),
        array('DNS', 'dijital-teknoloji'),
        array('Alan adı yönlendirme', 'dijital-teknoloji'),
        array('SSL sertifikası', 'dijital-teknoloji'),
        array('Veri şifreleme', 'dijital-teknoloji'),
        array('Hashleme', 'dijital-teknoloji'),
        array('Token', 'dijital-teknoloji'),
        array('Oturum açma', 'dijital-teknoloji'),
        array('Çıkış yapma (dijital)', 'dijital-teknoloji'),
        array('Kullanıcı doğrulama', 'dijital-teknoloji'),
        array('Dijital kimlik doğrulama', 'dijital-teknoloji'),
        array('İki faktörlü doğrulama', 'dijital-teknoloji'),
        array('Yetkilendirme', 'dijital-teknoloji'),
        array('Erişim kontrolü', 'dijital-teknoloji'),
        array('Kayıt defteri', 'dijital-teknoloji'),
        array('Log kaydı', 'dijital-teknoloji'),
        array('Veri yedekleme', 'dijital-teknoloji'),
        array('Felaket kurtarma', 'dijital-teknoloji'),
        array('Sanallaştırma', 'dijital-teknoloji'),
        array('Konteyner', 'dijital-teknoloji'),
        array('Docker', 'dijital-teknoloji'),
        array('Kubernetes', 'dijital-teknoloji'),
        array('API anahtarı', 'dijital-teknoloji'),
        array('OAuth', 'dijital-teknoloji'),
        array('Tek oturum açma (SSO)', 'dijital-teknoloji'),
        array('Açık veri', 'dijital-teknoloji'),
        array('Kapalı sistem', 'dijital-teknoloji'),
        array('Sürüm kontrolü', 'dijital-teknoloji'),
        array('Git', 'dijital-teknoloji'),
        array('Commit', 'dijital-teknoloji'),
        array('Branch', 'dijital-teknoloji'),
        array('Merge', 'dijital-teknoloji'),
        array('Pull request', 'dijital-teknoloji'),
        array('CI/CD', 'dijital-teknoloji'),
        array('Otomasyon', 'dijital-teknoloji'),
        array('Script', 'dijital-teknoloji'),
        array('Sunucu tarafı', 'dijital-teknoloji'),
        array('İstemci tarafı', 'dijital-teknoloji'),
        array('Frontend', 'dijital-teknoloji'),
        array('Backend', 'dijital-teknoloji'),
        array('Veritabanı', 'dijital-teknoloji'),
        array('SQL', 'dijital-teknoloji'),
        array('NoSQL', 'dijital-teknoloji'),
        array('Cache bellek', 'dijital-teknoloji'),
        array('RAM', 'dijital-teknoloji'),
        array('CPU', 'dijital-teknoloji'),
        array('GPU', 'dijital-teknoloji'),
        array('İşlemci çekirdeği', 'dijital-teknoloji'),
        array('Sanal makine', 'dijital-teknoloji'),
        array('Sanal sunucu', 'dijital-teknoloji'),
        array('Barındırma hizmeti', 'dijital-teknoloji'),
        array('CDN cache', 'dijital-teknoloji'),
        array('Veri sıkıştırma', 'dijital-teknoloji'),
        array('Yükleme süresi', 'dijital-teknoloji'),
        array('Sayfa hızı', 'dijital-teknoloji'),
        array('Core Web Vitals', 'dijital-teknoloji'),
        array('Lighthouse', 'dijital-teknoloji'),
        array('Performans metriği', 'dijital-teknoloji'),
        array('Erişilebilirlik', 'dijital-teknoloji'),
        array('Kullanılabilirlik', 'dijital-teknoloji'),
        array('UI', 'dijital-teknoloji'),
        array('UX', 'dijital-teknoloji'),
        
        // 💰 Ekonomi & Finans (551-600)
        array('Nakit akışı', 'ekonomi'),
        array('Gelir', 'ekonomi'),
        array('Gider', 'ekonomi'),
        array('Bilanço', 'ekonomi'),
        array('Gelir tablosu', 'ekonomi'),
        array('Karlılık', 'ekonomi'),
        array('Zarar', 'ekonomi'),
        array('Amortisman', 'ekonomi'),
        array('Varlık', 'ekonomi'),
        array('Yükümlülük (finans)', 'ekonomi'),
        array('Öz sermaye', 'ekonomi'),
        array('Net kâr', 'ekonomi'),
        array('Brüt kâr', 'ekonomi'),
        array('Marj', 'ekonomi'),
        array('Maliyet', 'ekonomi'),
        array('Sabit gider', 'ekonomi'),
        array('Değişken gider', 'ekonomi'),
        array('Envanter', 'ekonomi'),
        array('Stok', 'ekonomi'),
        array('Tedarik', 'ekonomi'),
        array('Tedarik zinciri', 'ekonomi'),
        array('Üretim', 'ekonomi'),
        array('Dağıtım', 'ekonomi'),
        array('Satış', 'ekonomi'),
        array('Fatura', 'ekonomi'),
        array('E-arşiv fatura', 'ekonomi'),
        array('E-fatura', 'ekonomi'),
        array('Tahsilat', 'ekonomi'),
        array('Ödeme', 'ekonomi'),
        array('POS', 'ekonomi'),
        array('Kart limiti', 'ekonomi'),
        array('Kredi kartı', 'ekonomi'),
        array('Asgari ödeme', 'ekonomi'),
        array('Gecikme faizi', 'ekonomi'),
        array('Temerrüt', 'ekonomi'),
        array('Haciz işlemi', 'ekonomi'),
        array('İcra dosyası', 'ekonomi'),
        array('Borç yapılandırma', 'ekonomi'),
        array('Finansman', 'ekonomi'),
        array('Leasing', 'ekonomi'),
        array('Faktoring', 'ekonomi'),
        array('Teminat', 'ekonomi'),
        array('Kefil', 'ekonomi'),
        array('Aval', 'ekonomi'),
        array('Sigorta primi', 'ekonomi'),
        array('Poliçe', 'ekonomi'),
        array('Hasar', 'ekonomi'),
        array('Tazmin', 'ekonomi'),
        array('Emeklilik yaşı', 'ekonomi'),
        array('Emekli maaşı', 'ekonomi'),
    );
    
    // Merge arrays
    $all_kavramlar = array_merge($kavramlar, $kavramlar_part2);
    
    // Import kavramlar
    $count = 0;
    foreach ($all_kavramlar as $kavram) {
        $title = $kavram[0];
        $category_slug = $kavram[1];
        
        // Check if already exists
        $existing = get_page_by_title($title, OBJECT, 'kavram');
        if ($existing) {
            continue;
        }
        
        // Create slug
        $slug = sanitize_title($title);
        
        // Insert post
        $post_id = wp_insert_post(array(
            'post_title'   => $title,
            'post_name'    => $slug,
            'post_type'    => 'kavram',
            'post_status'  => 'publish',
            'post_content' => '<!-- Açıklama eklenecek -->',
        ));
        
        if ($post_id && !is_wp_error($post_id)) {
            // Set category
            $term = get_term_by('slug', $category_slug, 'ana-kategori');
            if ($term) {
                wp_set_post_terms($post_id, array($term->term_id), 'ana-kategori');
            }
            
            // Set short definition placeholder
            update_post_meta($post_id, '_kavram_short_def', $title . ' nedir? (Açıklama eklenecek)');
            
            $count++;
        }
    }
    
    return $count;
}

// Add admin notice with import link
add_action('admin_notices', 'nedir_import_admin_notice');
function nedir_import_admin_notice() {
    if (get_option('nedir_kavramlar_imported')) {
        return;
    }
    
    if (!current_user_can('manage_options')) {
        return;
    }
    
    $import_url = admin_url('?import_kavramlar=1');
    ?>
    <div class="notice notice-info">
        <p><strong>Nedir.me:</strong> 1000 kavramı içe aktarmak için <a href="<?php echo esc_url($import_url); ?>">buraya tıklayın</a>.</p>
    </div>
    <?php
}
