<?php
/**
 * Nedir.me Kavram Import Script - Part 2 (601-1000)
 */

if (!defined('ABSPATH')) {
    exit;
}

add_action('admin_init', 'nedir_import_kavramlar_part2');

function nedir_import_kavramlar_part2() {
    if (get_option('nedir_kavramlar_part2_imported')) {
        return;
    }
    
    if (!current_user_can('manage_options')) {
        return;
    }
    
    if (!isset($_GET['import_kavramlar_part2'])) {
        return;
    }
    
    $kavramlar = array(
        // ⚖️ Hukuk (601-650)
        array('Resmi işlem', 'hukuk'),
        array('Kamu kurumu', 'hukuk'),
        array('Yetki', 'hukuk'),
        array('Yetkisizlik', 'hukuk'),
        array('Yetki belgesi', 'hukuk'),
        array('İzin belgesi', 'hukuk'),
        array('Ruhsat', 'hukuk'),
        array('Beyan', 'hukuk'),
        array('Beyanname', 'hukuk'),
        array('Bildirim (resmi)', 'hukuk'),
        array('Tebliğ', 'hukuk'),
        array('Tebliğ tarihi', 'hukuk'),
        array('İlan', 'hukuk'),
        array('Resmi gazete', 'hukuk'),
        array('Yönetmelik', 'hukuk'),
        array('Kanun', 'hukuk'),
        array('Tüzük', 'hukuk'),
        array('Genelge', 'hukuk'),
        array('Kararname', 'hukuk'),
        array('İdari işlem', 'hukuk'),
        array('İptal davası', 'hukuk'),
        array('Tam yargı davası', 'hukuk'),
        array('İstinaf', 'hukuk'),
        array('Temyiz', 'hukuk'),
        array('Kesin karar', 'hukuk'),
        array('UYAP', 'hukuk'),
        array('E-tebligat', 'hukuk'),
        array('E-devlet', 'hukuk'),
        array('Resmi kayıt', 'hukuk'),
        array('Sicil', 'hukuk'),
        array('Nüfus kaydı', 'hukuk'),
        array('İkametgah', 'hukuk'),
        array('Yerleşim yeri', 'hukuk'),
        array('Tebligat adresi', 'hukuk'),
        array('Vukuatlı nüfus kayıt örneği', 'hukuk'),
        array('Nüfus müdürlüğü', 'hukuk'),
        array('Kimlik belgesi', 'hukuk'),
        array('T.C. kimlik numarası', 'hukuk'),
        array('İmza sirküleri', 'hukuk'),
        array('Şirket yetkilisi', 'hukuk'),
        array('Ticaret sicili', 'hukuk'),
        array('Vergi levhası', 'hukuk'),
        array('Kuruluş bildirimi', 'hukuk'),
        array('Tasfiye', 'hukuk'),
        array('Kapanış işlemi', 'hukuk'),
        array('Resmi defter', 'hukuk'),
        array('Yevmiye defteri', 'hukuk'),
        array('Envanter defteri', 'hukuk'),
        array('Defter-i kebir', 'hukuk'),
        array('E-defter', 'hukuk'),
        
        // 🩺 Sağlık & Beden (651-720)
        array('Vücut ısısı', 'saglik'),
        array('Ateşli hastalık', 'saglik'),
        array('Bağışıklık yanıtı', 'saglik'),
        array('İnflamasyon', 'saglik'),
        array('Enfeksiyon etkeni', 'saglik'),
        array('Virüs yükü', 'saglik'),
        array('Antikor', 'saglik'),
        array('Antijen', 'saglik'),
        array('Lenf sistemi', 'saglik'),
        array('Lenf bezi', 'saglik'),
        array('Dalak', 'saglik'),
        array('Kemik iliği', 'saglik'),
        array('Kırmızı kan hücresi', 'saglik'),
        array('Beyaz kan hücresi', 'saglik'),
        array('Hemoglobin', 'saglik'),
        array('Oksijenlenme', 'saglik'),
        array('Solunum sayısı', 'saglik'),
        array('Kan basıncı', 'saglik'),
        array('Sistolik', 'saglik'),
        array('Diyastolik', 'saglik'),
        array('Dolaşım sistemi', 'saglik'),
        array('Kardiyovasküler sistem', 'saglik'),
        array('Kalp ritmi', 'saglik'),
        array('Aritmi', 'saglik'),
        array('Hipertansiyon', 'saglik'),
        array('Hipotansiyon', 'saglik'),
        array('Hipo', 'saglik'),
        array('Hiper', 'saglik'),
        array('Elektrolit', 'saglik'),
        array('Sodyum', 'saglik'),
        array('Potasyum', 'saglik'),
        array('Kalsiyum', 'saglik'),
        array('Magnezyum', 'saglik'),
        array('Fosfor', 'saglik'),
        array('Demir', 'saglik'),
        array('Çinko', 'saglik'),
        array('B12 vitamini', 'saglik'),
        array('D vitamini', 'saglik'),
        array('C vitamini', 'saglik'),
        array('A vitamini', 'saglik'),
        array('E vitamini', 'saglik'),
        array('K vitamini', 'saglik'),
        array('Omega 3', 'saglik'),
        array('Omega 6', 'saglik'),
        array('Protein', 'saglik'),
        array('Karbonhidrat', 'saglik'),
        array('Yağ', 'saglik'),
        array('Lif', 'saglik'),
        array('Su dengesi', 'saglik'),
        array('İdrar', 'saglik'),
        array('Böbrek fonksiyonu', 'saglik'),
        array('Kreatinin', 'saglik'),
        array('Üre', 'saglik'),
        array('Karaciğer fonksiyonu', 'saglik'),
        array('ALT', 'saglik'),
        array('AST', 'saglik'),
        array('Bilirubin', 'saglik'),
        array('Safra', 'saglik'),
        array('Pankreas', 'saglik'),
        array('İnsülin direnci', 'saglik'),
        array('HbA1c', 'saglik'),
        array('Asidoz', 'saglik'),
        array('Alkaloz', 'saglik'),
        array('Vücut sıvıları', 'saglik'),
        array('Lenf sıvısı', 'saglik'),
        array('Sinir iletimi', 'saglik'),
        array('Nörotransmitter', 'saglik'),
        array('Sinaps', 'saglik'),
        array('Duyu organları', 'saglik'),
        array('Refleks yayı', 'saglik'),
        
        // 🎓 Eğitim & Okul (721-780)
        array('Okul öncesi', 'egitim'),
        array('İlkokul', 'egitim'),
        array('Ortaokul', 'egitim'),
        array('Lise', 'egitim'),
        array('Üniversite', 'egitim'),
        array('Fakülte', 'egitim'),
        array('Bölüm', 'egitim'),
        array('Program', 'egitim'),
        array('Kredi (AKTS)', 'egitim'),
        array('Ders kredisi', 'egitim'),
        array('Not ortalaması', 'egitim'),
        array('Transkript', 'egitim'),
        array('Yatay geçiş', 'egitim'),
        array('Dikey geçiş', 'egitim'),
        array('Açık öğretim', 'egitim'),
        array('Uzaktan eğitim', 'egitim'),
        array('Akademik takvim', 'egitim'),
        array('Kayıt yenileme', 'egitim'),
        array('Harç', 'egitim'),
        array('Muafiyet', 'egitim'),
        array('Staj', 'egitim'),
        array('Zorunlu staj', 'egitim'),
        array('Seçmeli staj', 'egitim'),
        array('Akademik danışman', 'egitim'),
        array('Bitirme projesi', 'egitim'),
        array('Tez', 'egitim'),
        array('Danışman öğretim üyesi', 'egitim'),
        array('Jüri', 'egitim'),
        array('Savunma', 'egitim'),
        array('Akademik etik', 'egitim'),
        array('İntihal', 'egitim'),
        array('Turnitin', 'egitim'),
        array('Kaynakça', 'egitim'),
        array('Alıntı', 'egitim'),
        array('Atıf', 'egitim'),
        array('Bibliyografya', 'egitim'),
        array('Makale', 'egitim'),
        array('Bildiri', 'egitim'),
        array('Sempozyum', 'egitim'),
        array('Kongre', 'egitim'),
        array('Yayın', 'egitim'),
        array('Hakem', 'egitim'),
        array('Hakemli dergi', 'egitim'),
        array('Açık erişim', 'egitim'),
        array('DOI', 'egitim'),
        array('ISBN', 'egitim'),
        array('ISSN', 'egitim'),
        array('Kütüphane', 'egitim'),
        array('Veri tabanı (akademik)', 'egitim'),
        array('Akademik arama', 'egitim'),
        array('Google Scholar', 'egitim'),
        array('YÖK', 'egitim'),
        array('YÖKSİS', 'egitim'),
        array('ÖSYM', 'egitim'),
        array('ALES', 'egitim'),
        array('YDS', 'egitim'),
        array('TUS', 'egitim'),
        array('DUS', 'egitim'),
        array('KPSS A', 'egitim'),
        array('KPSS B', 'egitim'),
        
        // 🌍 Sosyal & Günlük Dil (781-850)
        array('Toplumsal norm', 'sosyal'),
        array('Görgü kuralı', 'sosyal'),
        array('Etik', 'sosyal'),
        array('Ahlak', 'sosyal'),
        array('Sosyal rol', 'sosyal'),
        array('Statü', 'sosyal'),
        array('Prestij', 'sosyal'),
        array('Sosyal sermaye', 'sosyal'),
        array('Sosyal ağ', 'sosyal'),
        array('İtibar', 'sosyal'),
        array('Güven', 'sosyal'),
        array('Mahremiyet', 'sosyal'),
        array('Gizlilik', 'sosyal'),
        array('Özel alan', 'sosyal'),
        array('Kamusal alan', 'sosyal'),
        array('Toplumsal baskı', 'sosyal'),
        array('Kalıp yargı', 'sosyal'),
        array('Önyargı', 'sosyal'),
        array('Ayrımcılık', 'sosyal'),
        array('Eşitlik', 'sosyal'),
        array('Adalet', 'sosyal'),
        array('Sorumluluk bilinci', 'sosyal'),
        array('Dayanışma', 'sosyal'),
        array('Yardımlaşma', 'sosyal'),
        array('Gönüllülük', 'sosyal'),
        array('Sosyal aidiyet', 'sosyal'),
        array('Sosyal izolasyon (toplumsal)', 'sosyal'),
        array('Yabancılaşma', 'sosyal'),
        array('Kentleşme', 'sosyal'),
        array('Göç', 'sosyal'),
        array('Uyum', 'sosyal'),
        array('Kültür', 'sosyal'),
        array('Gelenek', 'sosyal'),
        array('Görenek', 'sosyal'),
        array('Değer yargısı', 'sosyal'),
        array('Toplumsal cinsiyet', 'sosyal'),
        array('Kimlik algısı', 'sosyal'),
        array('Sosyal mesafe', 'sosyal'),
        array('Sosyal etkileşim', 'sosyal'),
        array('İletişim', 'sosyal'),
        array('Beden dili', 'sosyal'),
        array('Sözsüz iletişim', 'sosyal'),
        array('Tonlama', 'sosyal'),
        array('Empatik iletişim', 'sosyal'),
        array('Çatışma', 'sosyal'),
        array('Uzlaşma (sosyal)', 'sosyal'),
        array('Arabuluculuk (sosyal)', 'sosyal'),
        array('İkna', 'sosyal'),
        array('Manipülasyon', 'sosyal'),
        array('Sosyal etki', 'sosyal'),
        array('Liderlik', 'sosyal'),
        array('Takipçilik', 'sosyal'),
        array('Grup dinamiği', 'sosyal'),
        array('Sosyal öğrenme', 'sosyal'),
        array('Rol model', 'sosyal'),
        array('İmaj', 'sosyal'),
        array('Algı yönetimi', 'sosyal'),
        array('Sosyal medya kimliği', 'sosyal'),
        array('Dijital itibar', 'sosyal'),
        array('Toplumsal bilinç', 'sosyal'),
        array('Kolektif bilinç', 'sosyal'),
        array('Toplumsal hafıza', 'sosyal'),
        array('Kamuoyu', 'sosyal'),
        array('Gündem', 'sosyal'),
        array('Sosyal sorumluluk', 'sosyal'),
        array('Şeffaflık', 'sosyal'),
        array('Hesap verebilirlik', 'sosyal'),
        array('Katılım', 'sosyal'),
        array('Sivil toplum', 'sosyal'),
        array('STK', 'sosyal'),
        
        // 🌐 Dijital & İnternet Dili (851-920)
        array('Feed', 'dijital-teknoloji'),
        array('Akış', 'dijital-teknoloji'),
        array('Story süresi', 'dijital-teknoloji'),
        array('Keşfet algoritması', 'dijital-teknoloji'),
        array('Trend topic', 'dijital-teknoloji'),
        array('Retweet', 'dijital-teknoloji'),
        array('Repost', 'dijital-teknoloji'),
        array('Mention', 'dijital-teknoloji'),
        array('Tag', 'dijital-teknoloji'),
        array('Sabitleme', 'dijital-teknoloji'),
        array('Pin', 'dijital-teknoloji'),
        array('Draft', 'dijital-teknoloji'),
        array('Taslak', 'dijital-teknoloji'),
        array('Bildirim ayarları', 'dijital-teknoloji'),
        array('Sessize alma modu', 'dijital-teknoloji'),
        array('Engellenenler', 'dijital-teknoloji'),
        array('Raporlanan içerik', 'dijital-teknoloji'),
        array('Topluluk kuralları', 'dijital-teknoloji'),
        array('Gizlilik ayarları', 'dijital-teknoloji'),
        array('İçerik filtresi', 'dijital-teknoloji'),
        array('İçerik politikası', 'dijital-teknoloji'),
        array('Telif hakkı', 'dijital-teknoloji'),
        array('DM isteği', 'dijital-teknoloji'),
        array('Hikâye yanıtı', 'dijital-teknoloji'),
        array('Close friends', 'dijital-teknoloji'),
        array('Arşiv', 'dijital-teknoloji'),
        array('Arama geçmişi', 'dijital-teknoloji'),
        array('Önbellek temizleme', 'dijital-teknoloji'),
        array('Veri silme', 'dijital-teknoloji'),
        array('Dijital detoks', 'dijital-teknoloji'),
        array('Bildirim kapatma', 'dijital-teknoloji'),
        array('Hesap dondurma', 'dijital-teknoloji'),
        array('Hesap silme', 'dijital-teknoloji'),
        array('İki adımlı güvenlik', 'dijital-teknoloji'),
        array('Kurtarma kodu', 'dijital-teknoloji'),
        array('Giriş denemesi', 'dijital-teknoloji'),
        array('Oturum süresi', 'dijital-teknoloji'),
        array('Hesap güvenliği', 'dijital-teknoloji'),
        array('Kimlik doğrulama', 'dijital-teknoloji'),
        array('Spam bildirimi', 'dijital-teknoloji'),
        array('Bot ağları', 'dijital-teknoloji'),
        array('Sahte etkileşim', 'dijital-teknoloji'),
        array('Shadow ban', 'dijital-teknoloji'),
        array('İçerik görünürlüğü', 'dijital-teknoloji'),
        array('Algoritmik ceza', 'dijital-teknoloji'),
        array('Hesap doğrulama', 'dijital-teknoloji'),
        array('Mavi tik', 'dijital-teknoloji'),
        array('İçerik erişimi', 'dijital-teknoloji'),
        array('Kapsam', 'dijital-teknoloji'),
        array('Erişim istatistiği', 'dijital-teknoloji'),
        array('Etkileşim oranı', 'dijital-teknoloji'),
        array('Görüntülenme', 'dijital-teknoloji'),
        array('Tıklanma', 'dijital-teknoloji'),
        array('Gösterim', 'dijital-teknoloji'),
        array('Kaydetme', 'dijital-teknoloji'),
        array('Paylaşma', 'dijital-teknoloji'),
        array('İzlenme süresi', 'dijital-teknoloji'),
        array('Çıkma oranı', 'dijital-teknoloji'),
        array('Trafik kaynağı', 'dijital-teknoloji'),
        array('Organik trafik', 'dijital-teknoloji'),
        array('Yönlendirme trafiği', 'dijital-teknoloji'),
        array('Sosyal trafik', 'dijital-teknoloji'),
        array('UTM kodu', 'dijital-teknoloji'),
        array('Kampanya takibi', 'dijital-teknoloji'),
        array('Dönüşüm', 'dijital-teknoloji'),
        array('Hedef tamamlama', 'dijital-teknoloji'),
        array('Analitik panel', 'dijital-teknoloji'),
        array('Gerçek zamanlı veri', 'dijital-teknoloji'),
        array('Veri görselleştirme', 'dijital-teknoloji'),
        array('Raporlama (dijital)', 'dijital-teknoloji'),
        
        // 🧩 Genel & Soyut Kavramlar (921-1000)
        array('Sistem', 'genel'),
        array('Yapı', 'genel'),
        array('Model', 'genel'),
        array('Çerçeve', 'genel'),
        array('Süreç', 'genel'),
        array('Döngü', 'genel'),
        array('Aşama', 'genel'),
        array('Basamak', 'genel'),
        array('Denge', 'genel'),
        array('Kaos', 'genel'),
        array('Karmaşıklık', 'genel'),
        array('Basitlik', 'genel'),
        array('Netlik', 'genel'),
        array('Belirsizlik', 'genel'),
        array('Olasılık', 'genel'),
        array('Risk algısı', 'genel'),
        array('Senaryo', 'genel'),
        array('Varsayım', 'genel'),
        array('Tahmin', 'genel'),
        array('Veri seti', 'genel'),
        array('Ölçüt', 'genel'),
        array('Kriter', 'genel'),
        array('Standart', 'genel'),
        array('Kalite', 'genel'),
        array('Performans', 'genel'),
        array('Verimlilik', 'genel'),
        array('Etkinlik', 'genel'),
        array('Optimizasyon', 'genel'),
        array('Strateji', 'genel'),
        array('Taktik', 'genel'),
        array('Planlama', 'genel'),
        array('Organizasyon', 'genel'),
        array('Yönetim', 'genel'),
        array('Liderlik tarzı', 'genel'),
        array('Karar mekanizması', 'genel'),
        array('Yetkinlik', 'genel'),
        array('Kapasite', 'genel'),
        array('Potansiyel', 'genel'),
        array('Sınır', 'genel'),
        array('Limit', 'genel'),
        array('Kapsam (genel)', 'genel'),
        array('Alan', 'genel'),
        array('Seviye', 'genel'),
        array('Derece', 'genel'),
        array('Ölçek', 'genel'),
        array('Hiyerarşi', 'genel'),
        array('Merkez', 'genel'),
        array('Çevre', 'genel'),
        array('Çekirdek', 'genel'),
        array('Katman', 'genel'),
        array('Boyut', 'genel'),
        array('Perspektif', 'genel'),
        array('Yaklaşım', 'genel'),
        array('Metodoloji', 'genel'),
        array('İlke', 'genel'),
        array('Kural', 'genel'),
        array('Norm', 'genel'),
        array('Değer (genel)', 'genel'),
        array('Ölçüm', 'genel'),
        array('Gösterge', 'genel'),
        array('Endeks (genel)', 'genel'),
        array('Parametre', 'genel'),
        array('Değişken', 'genel'),
        array('Sabit', 'genel'),
        array('Fonksiyon', 'genel'),
        array('Girdi', 'genel'),
        array('Çıktı', 'genel'),
        array('Sonuç', 'genel'),
        array('Etki', 'genel'),
        array('Tepki (genel)', 'genel'),
        array('Geri bildirim', 'genel'),
        array('İyileştirme', 'genel'),
        array('Gelişim', 'genel'),
        array('Evrim', 'genel'),
        array('Adaptasyon', 'genel'),
        array('Uyum sağlama', 'genel'),
        array('Sürdürülebilirlik', 'genel'),
        array('Süreklilik', 'genel'),
        array('Tutarlılık', 'genel'),
        array('Bütünlük', 'genel'),
    );
    
    // Create genel category if not exists
    if (!term_exists('genel', 'ana-kategori')) {
        wp_insert_term('Genel Kavramlar', 'ana-kategori', array(
            'slug' => 'genel',
            'description' => '🧩 Soyut ve genel kavramlar',
        ));
    }
    
    $count = 0;
    foreach ($kavramlar as $kavram) {
        $title = $kavram[0];
        $category_slug = $kavram[1];
        
        $existing = get_page_by_title($title, OBJECT, 'kavram');
        if ($existing) {
            continue;
        }
        
        $slug = sanitize_title($title);
        
        $post_id = wp_insert_post(array(
            'post_title'   => $title,
            'post_name'    => $slug,
            'post_type'    => 'kavram',
            'post_status'  => 'publish',
            'post_content' => '<!-- Açıklama eklenecek -->',
        ));
        
        if ($post_id && !is_wp_error($post_id)) {
            $term = get_term_by('slug', $category_slug, 'ana-kategori');
            if ($term) {
                wp_set_post_terms($post_id, array($term->term_id), 'ana-kategori');
            }
            
            update_post_meta($post_id, '_kavram_short_def', $title . ' nedir? (Açıklama eklenecek)');
            $count++;
        }
    }
    
    update_option('nedir_kavramlar_part2_imported', true);
    wp_die('Part 2 import tamamlandı! ' . $count . ' kavram eklendi. <a href="' . admin_url('edit.php?post_type=kavram') . '">Kavramları Gör</a>');
}

add_action('admin_notices', 'nedir_import_part2_notice');
function nedir_import_part2_notice() {
    if (get_option('nedir_kavramlar_part2_imported')) {
        return;
    }
    
    if (!get_option('nedir_kavramlar_imported')) {
        return;
    }
    
    if (!current_user_can('manage_options')) {
        return;
    }
    
    $import_url = admin_url('?import_kavramlar_part2=1');
    ?>
    <div class="notice notice-info">
        <p><strong>Nedir.me:</strong> Kalan ~400 kavramı içe aktarmak için <a href="<?php echo esc_url($import_url); ?>">buraya tıklayın</a> (Part 2).</p>
    </div>
    <?php
}
