<?php
/**
 * Nedir.me - Part 2 Kavramlar (401-700)
 */

if (!defined('ABSPATH')) exit;

function nedir_get_kavramlar_part2() {
    return array(
        // 🧠 İnsan & Zihin Part 2 (401-480)
        array('İçsel motivasyon', 'insan-zihin'),
        array('Dışsal motivasyon', 'insan-zihin'),
        array('Öz disiplin', 'insan-zihin'),
        array('İrade gücü', 'insan-zihin'),
        array('Kararlılık', 'insan-zihin'),
        array('Azim', 'insan-zihin'),
        array('Sabit fikir', 'insan-zihin'),
        array('Esneklik', 'insan-zihin'),
        array('Psikolojik dayanıklılık', 'insan-zihin'),
        array('Ruh hali', 'insan-zihin'),
        array('Duygusal dalgalanma', 'insan-zihin'),
        array('Duygusal tükenme', 'insan-zihin'),
        array('Duygusal boşluk', 'insan-zihin'),
        array('Ait olma ihtiyacı', 'insan-zihin'),
        array('Kabul görme ihtiyacı', 'insan-zihin'),
        array('Değer görme ihtiyacı', 'insan-zihin'),
        array('Anlam arayışı', 'insan-zihin'),
        array('Varoluşsal kaygı', 'insan-zihin'),
        array('Kimlik krizi', 'insan-zihin'),
        array('Rol karmaşası', 'insan-zihin'),
        array('Sosyal izolasyon', 'insan-zihin'),
        array('Sosyal bağ', 'insan-zihin'),
        array('Güven ihtiyacı', 'insan-zihin'),
        array('Kontrol duygusu', 'insan-zihin'),
        array('Kayıp korkusu', 'insan-zihin'),
        array('Başarısızlık korkusu', 'insan-zihin'),
        array('Onay arayışı', 'insan-zihin'),
        array('Yetersizlik algısı', 'insan-zihin'),
        array('Utanç duygusu', 'insan-zihin'),
        array('Suçluluk duygusu', 'insan-zihin'),
        array('Hayal kırıklığı eşiği', 'insan-zihin'),
        array('Umut seviyesi', 'insan-zihin'),
        array('Psikolojik sınır', 'insan-zihin'),
        array('Kişisel alan', 'insan-zihin'),
        array('Mental yük', 'insan-zihin'),
        array('Zihinsel esneklik', 'insan-zihin'),
        array('Zihinsel direnç', 'insan-zihin'),
        array('Zihinsel dayanıklılık', 'insan-zihin'),
        array('İç denge', 'insan-zihin'),
        array('Ruhsal denge', 'insan-zihin'),
        array('İç huzur hali', 'insan-zihin'),
        array('Duygusal farkındalık', 'insan-zihin'),
        array('Öz farkındalık', 'insan-zihin'),
        array('Kendini kabul', 'insan-zihin'),
        array('Kendini suçlama', 'insan-zihin'),
        array('Kendini sabote etme', 'insan-zihin'),
        array('Negatif düşünce döngüsü', 'insan-zihin'),
        array('Aşırı genelleme', 'insan-zihin'),
        array('Zihin okuma', 'insan-zihin'),
        array('Felaket senaryosu', 'insan-zihin'),
        array('Olumsuz filtre', 'insan-zihin'),
        array('Kutuplaşmış düşünme', 'insan-zihin'),
        array('Kişisel alma', 'insan-zihin'),
        array('Seçici algı', 'insan-zihin'),
        array('Kendilik değeri', 'insan-zihin'),
        array('Benlik saygısı', 'insan-zihin'),
        array('Kırılganlık', 'insan-zihin'),
        array('İçsel güven', 'insan-zihin'),
        array('Psikolojik esneklik', 'insan-zihin'),
        array('Duygusal regülasyon', 'insan-zihin'),
        array('Öz kontrol', 'insan-zihin'),
        array('İçsel denge', 'insan-zihin'),
        array('Ruhsal istikrar', 'insan-zihin'),
        array('Duygusal bağlanma', 'insan-zihin'),
        array('Güvenli bağlanma', 'insan-zihin'),
        array('Kaygılı bağlanma', 'insan-zihin'),
        array('Kaçıngan bağlanma', 'insan-zihin'),
        array('Travma tepkisi', 'insan-zihin'),
        array('Psikolojik tetikleyici', 'insan-zihin'),
        array('Duygusal tetiklenme', 'insan-zihin'),
        array('Psikolojik yük', 'insan-zihin'),
        array('Zihinsel yıpranma', 'insan-zihin'),
        array('Ruhsal yorgunluk', 'insan-zihin'),
        array('Mental blokaj', 'insan-zihin'),
        array('İçsel karmaşa', 'insan-zihin'),
        array('Psikolojik çöküş', 'insan-zihin'),
        array('Ruhsal kırılma', 'insan-zihin'),
        array('İçsel toparlanma', 'insan-zihin'),
        
        // 💻 Teknoloji Part 2 (481-550)
        array('Dijital okuryazarlık', 'dijital-teknoloji'),
        array('Veri güvenliği', 'dijital-teknoloji'),
        array('Sunucu yükü', 'dijital-teknoloji'),
        array('Bant genişliği', 'dijital-teknoloji'),
        array('Ping', 'dijital-teknoloji'),
        array('Gecikme süresi', 'dijital-teknoloji'),
        array('Paket kaybı', 'dijital-teknoloji'),
        array('Yük dengeleme', 'dijital-teknoloji'),
        array('CDN', 'dijital-teknoloji'),
        array('DNS', 'dijital-teknoloji'),
        array('SSL sertifikası', 'dijital-teknoloji'),
        array('Veri şifreleme', 'dijital-teknoloji'),
        array('Hashleme', 'dijital-teknoloji'),
        array('Token', 'dijital-teknoloji'),
        array('İki faktörlü doğrulama', 'dijital-teknoloji'),
        array('Yetkilendirme', 'dijital-teknoloji'),
        array('Erişim kontrolü', 'dijital-teknoloji'),
        array('Log kaydı', 'dijital-teknoloji'),
        array('Veri yedekleme', 'dijital-teknoloji'),
        array('Felaket kurtarma', 'dijital-teknoloji'),
        array('Sanallaştırma', 'dijital-teknoloji'),
        array('Docker', 'dijital-teknoloji'),
        array('Kubernetes', 'dijital-teknoloji'),
        array('API anahtarı', 'dijital-teknoloji'),
        array('OAuth', 'dijital-teknoloji'),
        array('SSO', 'dijital-teknoloji'),
        array('Açık kaynak', 'dijital-teknoloji'),
        array('Sürüm kontrolü', 'dijital-teknoloji'),
        array('Git', 'dijital-teknoloji'),
        array('Commit', 'dijital-teknoloji'),
        array('Branch', 'dijital-teknoloji'),
        array('Merge', 'dijital-teknoloji'),
        array('Pull request', 'dijital-teknoloji'),
        array('CI/CD', 'dijital-teknoloji'),
        array('Frontend', 'dijital-teknoloji'),
        array('Backend', 'dijital-teknoloji'),
        array('Veritabanı', 'dijital-teknoloji'),
        array('SQL', 'dijital-teknoloji'),
        array('NoSQL', 'dijital-teknoloji'),
        array('RAM', 'dijital-teknoloji'),
        array('CPU', 'dijital-teknoloji'),
        array('GPU', 'dijital-teknoloji'),
        array('Sanal makine', 'dijital-teknoloji'),
        array('Core Web Vitals', 'dijital-teknoloji'),
        array('UI', 'dijital-teknoloji'),
        array('UX', 'dijital-teknoloji'),
        
        // 💰 Ekonomi Part 2 (551-600)
        array('Nakit akışı', 'ekonomi'),
        array('Gelir', 'ekonomi'),
        array('Gider', 'ekonomi'),
        array('Bilanço', 'ekonomi'),
        array('Gelir tablosu', 'ekonomi'),
        array('Karlılık', 'ekonomi'),
        array('Zarar', 'ekonomi'),
        array('Amortisman', 'ekonomi'),
        array('Varlık', 'ekonomi'),
        array('Öz sermaye', 'ekonomi'),
        array('Net kâr', 'ekonomi'),
        array('Brüt kâr', 'ekonomi'),
        array('Marj', 'ekonomi'),
        array('Maliyet', 'ekonomi'),
        array('Sabit gider', 'ekonomi'),
        array('Değişken gider', 'ekonomi'),
        array('Envanter', 'ekonomi'),
        array('Stok', 'ekonomi'),
        array('Tedarik', 'ekonomi'),
        array('Tedarik zinciri', 'ekonomi'),
        array('Üretim', 'ekonomi'),
        array('Dağıtım', 'ekonomi'),
        array('Satış', 'ekonomi'),
        array('Fatura', 'ekonomi'),
        array('E-fatura', 'ekonomi'),
        array('Tahsilat', 'ekonomi'),
        array('Ödeme', 'ekonomi'),
        array('POS', 'ekonomi'),
        array('Kredi kartı', 'ekonomi'),
        array('Asgari ödeme', 'ekonomi'),
        array('Gecikme faizi', 'ekonomi'),
        array('Temerrüt', 'ekonomi'),
        array('Borç yapılandırma', 'ekonomi'),
        array('Finansman', 'ekonomi'),
        array('Leasing', 'ekonomi'),
        array('Faktoring', 'ekonomi'),
        array('Teminat', 'ekonomi'),
        array('Kefil', 'ekonomi'),
        array('Sigorta primi', 'ekonomi'),
        array('Poliçe', 'ekonomi'),
        array('Hasar', 'ekonomi'),
        array('Emekli maaşı', 'ekonomi'),
        
        // ⚖️ Hukuk Part 2 (601-650)
        array('Resmi işlem', 'hukuk'),
        array('Kamu kurumu', 'hukuk'),
        array('Yetki belgesi', 'hukuk'),
        array('İzin belgesi', 'hukuk'),
        array('Ruhsat', 'hukuk'),
        array('Beyan', 'hukuk'),
        array('Beyanname', 'hukuk'),
        array('Tebliğ', 'hukuk'),
        array('Resmi gazete', 'hukuk'),
        array('Yönetmelik', 'hukuk'),
        array('Tüzük', 'hukuk'),
        array('Genelge', 'hukuk'),
        array('Kararname', 'hukuk'),
        array('İdari işlem', 'hukuk'),
        array('İptal davası', 'hukuk'),
        array('İstinaf', 'hukuk'),
        array('Temyiz', 'hukuk'),
        array('Kesin karar', 'hukuk'),
        array('UYAP', 'hukuk'),
        array('E-tebligat', 'hukuk'),
        array('Nüfus kaydı', 'hukuk'),
        array('İkametgah', 'hukuk'),
        array('T.C. kimlik numarası', 'hukuk'),
        array('İmza sirküleri', 'hukuk'),
        array('Ticaret sicili', 'hukuk'),
        array('Vergi levhası', 'hukuk'),
        array('Tasfiye', 'hukuk'),
        array('Yevmiye defteri', 'hukuk'),
        array('E-defter', 'hukuk'),
        
        // 🩺 Sağlık Part 2 (651-720)
        array('Vücut ısısı', 'saglik'),
        array('Bağışıklık yanıtı', 'saglik'),
        array('İnflamasyon', 'saglik'),
        array('Virüs yükü', 'saglik'),
        array('Antikor', 'saglik'),
        array('Antijen', 'saglik'),
        array('Lenf sistemi', 'saglik'),
        array('Lenf bezi', 'saglik'),
        array('Dalak', 'saglik'),
        array('Kemik iliği', 'saglik'),
        array('Kırmızı kan hücresi', 'saglik'),
        array('Beyaz kan hücresi', 'saglik'),
        array('Hemoglobin', 'saglik'),
        array('Oksijenlenme', 'saglik'),
        array('Kan basıncı', 'saglik'),
        array('Sistolik', 'saglik'),
        array('Diyastolik', 'saglik'),
        array('Kardiyovasküler sistem', 'saglik'),
        array('Kalp ritmi', 'saglik'),
        array('Aritmi', 'saglik'),
        array('Hipertansiyon', 'saglik'),
        array('Hipotansiyon', 'saglik'),
        array('Elektrolit', 'saglik'),
        array('Sodyum', 'saglik'),
        array('Potasyum', 'saglik'),
        array('Kalsiyum', 'saglik'),
        array('Magnezyum', 'saglik'),
        array('Demir', 'saglik'),
        array('Çinko', 'saglik'),
        array('B12 vitamini', 'saglik'),
        array('D vitamini', 'saglik'),
        array('C vitamini', 'saglik'),
        array('Omega 3', 'saglik'),
        array('Lif', 'saglik'),
        array('Su dengesi', 'saglik'),
        array('Böbrek fonksiyonu', 'saglik'),
        array('Kreatinin', 'saglik'),
        array('Üre', 'saglik'),
        array('Karaciğer fonksiyonu', 'saglik'),
        array('ALT', 'saglik'),
        array('AST', 'saglik'),
        array('Bilirubin', 'saglik'),
        array('Safra', 'saglik'),
        array('Pankreas', 'saglik'),
        array('İnsülin direnci', 'saglik'),
        array('HbA1c', 'saglik'),
        array('Nörotransmitter', 'saglik'),
        array('Sinaps', 'saglik'),
        array('Duyu organları', 'saglik'),
        array('Refleks yayı', 'saglik'),
        
        // 🎓 Eğitim Part 2 (721-780)
        array('Okul öncesi', 'egitim'),
        array('İlkokul', 'egitim'),
        array('Ortaokul', 'egitim'),
        array('Lise', 'egitim'),
        array('Bölüm', 'egitim'),
        array('AKTS', 'egitim'),
        array('Not ortalaması', 'egitim'),
        array('Transkript', 'egitim'),
        array('Yatay geçiş', 'egitim'),
        array('Dikey geçiş', 'egitim'),
        array('Açık öğretim', 'egitim'),
        array('Uzaktan eğitim', 'egitim'),
        array('Akademik takvim', 'egitim'),
        array('Harç', 'egitim'),
        array('Muafiyet', 'egitim'),
        array('Zorunlu staj', 'egitim'),
        array('Bitirme projesi', 'egitim'),
        array('Jüri', 'egitim'),
        array('Savunma', 'egitim'),
        array('Akademik etik', 'egitim'),
        array('Turnitin', 'egitim'),
        array('Alıntı', 'egitim'),
        array('Atıf', 'egitim'),
        array('Bildiri', 'egitim'),
        array('Sempozyum', 'egitim'),
        array('Kongre', 'egitim'),
        array('Hakemli dergi', 'egitim'),
        array('Açık erişim', 'egitim'),
        array('DOI', 'egitim'),
        array('ISBN', 'egitim'),
        array('ISSN', 'egitim'),
        array('YÖKSİS', 'egitim'),
        array('ALES', 'egitim'),
        array('YDS', 'egitim'),
        array('TUS', 'egitim'),
        
        // 🌐 Sosyal Part 2 (781-850)
        array('Toplumsal norm', 'sosyal'),
        array('Görgü kuralı', 'sosyal'),
        array('Sosyal rol', 'sosyal'),
        array('Statü', 'sosyal'),
        array('Sosyal sermaye', 'sosyal'),
        array('Sosyal ağ', 'sosyal'),
        array('Mahremiyet', 'sosyal'),
        array('Gizlilik', 'sosyal'),
        array('Özel alan', 'sosyal'),
        array('Kamusal alan', 'sosyal'),
        array('Toplumsal baskı', 'sosyal'),
        array('Kalıp yargı', 'sosyal'),
        array('Sorumluluk bilinci', 'sosyal'),
        array('Yardımlaşma', 'sosyal'),
        array('Gönüllülük', 'sosyal'),
        array('Sosyal aidiyet', 'sosyal'),
        array('Yabancılaşma', 'sosyal'),
        array('Kentleşme', 'sosyal'),
        array('Göç', 'sosyal'),
        array('Uyum', 'sosyal'),
        array('Görenek', 'sosyal'),
        array('Değer yargısı', 'sosyal'),
        array('Toplumsal cinsiyet', 'sosyal'),
        array('Sosyal mesafe', 'sosyal'),
        array('Sosyal etkileşim', 'sosyal'),
        array('İletişim', 'sosyal'),
        array('Beden dili', 'sosyal'),
        array('Sözsüz iletişim', 'sosyal'),
        array('Empatik iletişim', 'sosyal'),
        array('Çatışma', 'sosyal'),
        array('İkna', 'sosyal'),
        array('Manipülasyon', 'sosyal'),
        array('Sosyal etki', 'sosyal'),
        array('Grup dinamiği', 'sosyal'),
        array('Sosyal öğrenme', 'sosyal'),
        array('Rol model', 'sosyal'),
        array('İmaj', 'sosyal'),
        array('Algı yönetimi', 'sosyal'),
        array('Sosyal medya kimliği', 'sosyal'),
        array('Dijital itibar', 'sosyal'),
        array('Toplumsal bilinç', 'sosyal'),
        array('Kolektif bilinç', 'sosyal'),
        array('Toplumsal hafıza', 'sosyal'),
        array('Kamuoyu', 'sosyal'),
        array('Gündem', 'sosyal'),
        array('Sosyal sorumluluk', 'sosyal'),
        array('Şeffaflık', 'sosyal'),
        array('Hesap verebilirlik', 'sosyal'),
        array('Katılım', 'sosyal'),
        array('Sivil toplum', 'sosyal'),
        array('STK', 'sosyal'),
    );
}
