<?php
/**
 * Nedir.me - Full Import Function
 * This file contains all 1000 concepts for import
 */

if (!defined('ABSPATH')) exit;

function nedir_get_all_kavramlar() {
    return array(
        // 🧠 İnsan & Zihin (1-80)
        array('Stres', 'insan-zihin'),
        array('Kaygı', 'insan-zihin'),
        array('Anksiyete', 'insan-zihin'),
        array('Panik atak', 'insan-zihin'),
        array('Depresyon', 'insan-zihin'),
        array('Tükenmişlik', 'insan-zihin'),
        array('Motivasyon', 'insan-zihin'),
        array('Odak', 'insan-zihin'),
        array('Dikkat', 'insan-zihin'),
        array('Konsantrasyon', 'insan-zihin'),
        array('Alışkanlık', 'insan-zihin'),
        array('Erteleme', 'insan-zihin'),
        array('Özgüven', 'insan-zihin'),
        array('Özsaygı', 'insan-zihin'),
        array('Özşefkat', 'insan-zihin'),
        array('Yalnızlık', 'insan-zihin'),
        array('Kıskançlık', 'insan-zihin'),
        array('Utanç', 'insan-zihin'),
        array('Suçluluk', 'insan-zihin'),
        array('Sabır', 'insan-zihin'),
        array('Öfke', 'insan-zihin'),
        array('Stres hormonu', 'insan-zihin'),
        array('Travma', 'insan-zihin'),
        array('Fobi', 'insan-zihin'),
        array('Bağımlılık', 'insan-zihin'),
        array('Takıntı', 'insan-zihin'),
        array('Obsesyon', 'insan-zihin'),
        array('Bilinç', 'insan-zihin'),
        array('Bilinçaltı', 'insan-zihin'),
        array('Algı', 'insan-zihin'),
        array('Zihin', 'insan-zihin'),
        array('Farkındalık', 'insan-zihin'),
        array('Empati', 'insan-zihin'),
        array('Sempati', 'insan-zihin'),
        array('İrade', 'insan-zihin'),
        array('Karar verme', 'insan-zihin'),
        array('İç motivasyon', 'insan-zihin'),
        array('Dış motivasyon', 'insan-zihin'),
        array('Hedef', 'insan-zihin'),
        array('Niyet', 'insan-zihin'),
        array('Duygu', 'insan-zihin'),
        array('His', 'insan-zihin'),
        array('Mutluluk', 'insan-zihin'),
        array('Tatmin', 'insan-zihin'),
        array('Memnuniyet', 'insan-zihin'),
        array('Hayal kırıklığı', 'insan-zihin'),
        array('Umut', 'insan-zihin'),
        array('Umutsuzluk', 'insan-zihin'),
        array('Değer', 'insan-zihin'),
        array('İnanç', 'insan-zihin'),
        array('Düşünce', 'insan-zihin'),
        array('Düşünce kalıbı', 'insan-zihin'),
        array('Zihinsel yorgunluk', 'insan-zihin'),
        array('Beyin sisi', 'insan-zihin'),
        array('Zihinsel blokaj', 'insan-zihin'),
        array('Özgürlük hissi', 'insan-zihin'),
        array('Kontrol ihtiyacı', 'insan-zihin'),
        array('Kaçınma davranışı', 'insan-zihin'),
        array('Aşırı düşünme', 'insan-zihin'),
        array('Ruminasyon', 'insan-zihin'),
        array('Negatif iç ses', 'insan-zihin'),
        array('İç diyalog', 'insan-zihin'),
        array('Kendilik algısı', 'insan-zihin'),
        array('Benlik', 'insan-zihin'),
        array('Kimlik', 'insan-zihin'),
        array('Kişilik', 'insan-zihin'),
        array('Karakter', 'insan-zihin'),
        array('Tutum', 'insan-zihin'),
        array('Davranış', 'insan-zihin'),
        array('Tepki', 'insan-zihin'),
        array('Alışkanlık döngüsü', 'insan-zihin'),
        array('Otomatik düşünce', 'insan-zihin'),
        array('Bilişsel çarpıtma', 'insan-zihin'),
        array('Felaketleştirme', 'insan-zihin'),
        array('Siyah beyaz düşünme', 'insan-zihin'),
        array('Onay ihtiyacı', 'insan-zihin'),
        array('Yetersizlik hissi', 'insan-zihin'),
        array('Sosyal kaygı', 'insan-zihin'),
        array('Performans kaygısı', 'insan-zihin'),
        array('İç huzur', 'insan-zihin'),
        
        // 💻 Dijital & İnternet (81-150)
        array('Algoritma', 'dijital-teknoloji'),
        array('Yapay zeka', 'dijital-teknoloji'),
        array('Veri', 'dijital-teknoloji'),
        array('Dijital ayak izi', 'dijital-teknoloji'),
        array('Çerez (cookie)', 'dijital-teknoloji'),
        array('Bulut bilişim', 'dijital-teknoloji'),
        array('API', 'dijital-teknoloji'),
        array('Sunucu', 'dijital-teknoloji'),
        array('Tarayıcı', 'dijital-teknoloji'),
        array('Arama motoru', 'dijital-teknoloji'),
        array('SEO', 'dijital-teknoloji'),
        array('Backlink', 'dijital-teknoloji'),
        array('IP adresi', 'dijital-teknoloji'),
        array('VPN', 'dijital-teknoloji'),
        array('Firewall', 'dijital-teknoloji'),
        array('Spam', 'dijital-teknoloji'),
        array('Bot', 'dijital-teknoloji'),
        array('Troll', 'dijital-teknoloji'),
        array('Hashtag', 'dijital-teknoloji'),
        array('Influencer', 'dijital-teknoloji'),
        array('Viral içerik', 'dijital-teknoloji'),
        array('Deep web', 'dijital-teknoloji'),
        array('Dark web', 'dijital-teknoloji'),
        array('Blockchain', 'dijital-teknoloji'),
        array('NFT', 'dijital-teknoloji'),
        array('Kripto para', 'dijital-teknoloji'),
        array('Dijital cüzdan', 'dijital-teknoloji'),
        array('Akıllı sözleşme', 'dijital-teknoloji'),
        array('Metaverse', 'dijital-teknoloji'),
        array('Avatar', 'dijital-teknoloji'),
        array('Bulut depolama', 'dijital-teknoloji'),
        array('Dosya uzantısı', 'dijital-teknoloji'),
        array('PDF', 'dijital-teknoloji'),
        array('Cache', 'dijital-teknoloji'),
        array('Siber güvenlik', 'dijital-teknoloji'),
        array('Şifreleme', 'dijital-teknoloji'),
        array('İki adımlı doğrulama', 'dijital-teknoloji'),
        array('Phishing', 'dijital-teknoloji'),
        array('Domain', 'dijital-teknoloji'),
        array('Hosting', 'dijital-teknoloji'),
        array('HTTP', 'dijital-teknoloji'),
        array('HTTPS', 'dijital-teknoloji'),
        array('URL', 'dijital-teknoloji'),
        array('QR kod', 'dijital-teknoloji'),
        array('Wi-Fi', 'dijital-teknoloji'),
        array('Bluetooth', 'dijital-teknoloji'),
        array('E-posta', 'dijital-teknoloji'),
        array('Dijital bağımlılık', 'dijital-teknoloji'),
        array('Ekran süresi', 'dijital-teknoloji'),
        array('Yapay sinir ağı', 'dijital-teknoloji'),
        array('Makine öğrenmesi', 'dijital-teknoloji'),
        array('Büyük veri', 'dijital-teknoloji'),
        
        // 💰 Ekonomi (151-220)
        array('Enflasyon', 'ekonomi'),
        array('Faiz', 'ekonomi'),
        array('Arz', 'ekonomi'),
        array('Talep', 'ekonomi'),
        array('Piyasa', 'ekonomi'),
        array('Borsa', 'ekonomi'),
        array('Hisse senedi', 'ekonomi'),
        array('Endeks', 'ekonomi'),
        array('Likidite', 'ekonomi'),
        array('Resesyon', 'ekonomi'),
        array('Durgunluk', 'ekonomi'),
        array('Devalüasyon', 'ekonomi'),
        array('Döviz kuru', 'ekonomi'),
        array('Kriz', 'ekonomi'),
        array('GSYİH', 'ekonomi'),
        array('İstihdam', 'ekonomi'),
        array('İşsizlik', 'ekonomi'),
        array('Asgari ücret', 'ekonomi'),
        array('Vergi', 'ekonomi'),
        array('Gelir vergisi', 'ekonomi'),
        array('KDV', 'ekonomi'),
        array('Bütçe', 'ekonomi'),
        array('Borç', 'ekonomi'),
        array('Kredi', 'ekonomi'),
        array('Faiz oranı', 'ekonomi'),
        array('Merkez bankası', 'ekonomi'),
        array('Para politikası', 'ekonomi'),
        array('Alım gücü', 'ekonomi'),
        array('Yatırım', 'ekonomi'),
        array('Tasarruf', 'ekonomi'),
        array('Birikim', 'ekonomi'),
        array('Ekonomik büyüme', 'ekonomi'),
        array('İhracat', 'ekonomi'),
        array('İthalat', 'ekonomi'),
        array('Finansal okuryazarlık', 'ekonomi'),
        array('Risk', 'ekonomi'),
        array('Getiri', 'ekonomi'),
        array('Portföy', 'ekonomi'),
        array('Sermaye', 'ekonomi'),
        array('Temettü', 'ekonomi'),
        array('Bankacılık', 'ekonomi'),
        array('Kredi notu', 'ekonomi'),
        array('Sigorta', 'ekonomi'),
        array('Emeklilik', 'ekonomi'),
        array('Konut kredisi', 'ekonomi'),
        
        // ⚖️ Hukuk (221-270)
        array('Hukuk', 'hukuk'),
        array('Hak', 'hukuk'),
        array('Yükümlülük', 'hukuk'),
        array('Sorumluluk', 'hukuk'),
        array('Suç', 'hukuk'),
        array('Ceza', 'hukuk'),
        array('Dava', 'hukuk'),
        array('Mahkeme', 'hukuk'),
        array('Savcı', 'hukuk'),
        array('Hâkim', 'hukuk'),
        array('Avukat', 'hukuk'),
        array('İcra', 'hukuk'),
        array('Haciz', 'hukuk'),
        array('Tazminat', 'hukuk'),
        array('Sözleşme', 'hukuk'),
        array('İmza', 'hukuk'),
        array('Tebligat', 'hukuk'),
        array('İtiraz', 'hukuk'),
        array('Şikâyet', 'hukuk'),
        array('Uzlaşma', 'hukuk'),
        array('Arabuluculuk', 'hukuk'),
        array('Yargılama', 'hukuk'),
        array('Karar', 'hukuk'),
        array('Delil', 'hukuk'),
        array('Tanık', 'hukuk'),
        array('Sanık', 'hukuk'),
        array('Mağdur', 'hukuk'),
        array('Zamanaşımı', 'hukuk'),
        array('Dilekçe', 'hukuk'),
        array('Noter', 'hukuk'),
        array('Vekâlet', 'hukuk'),
        array('Miras', 'hukuk'),
        array('Vasiyet', 'hukuk'),
        array('Nafaka', 'hukuk'),
        array('Boşanma', 'hukuk'),
        array('İflas', 'hukuk'),
        array('Adli sicil', 'hukuk'),
        array('Sabıka kaydı', 'hukuk'),
        array('Kanun', 'hukuk'),
        array('E-devlet', 'hukuk'),
        
        // 🩺 Sağlık (271-330)
        array('Bağışıklık', 'saglik'),
        array('Vitamin', 'saglik'),
        array('Mineral', 'saglik'),
        array('Hormon', 'saglik'),
        array('Metabolizma', 'saglik'),
        array('Diyabet', 'saglik'),
        array('Tansiyon', 'saglik'),
        array('Kolesterol', 'saglik'),
        array('Alerji', 'saglik'),
        array('Virüs', 'saglik'),
        array('Bakteri', 'saglik'),
        array('Enfeksiyon', 'saglik'),
        array('Antibiyotik', 'saglik'),
        array('Aşı', 'saglik'),
        array('Bağışıklık sistemi', 'saglik'),
        array('Kalori', 'saglik'),
        array('Vücut kitle indeksi', 'saglik'),
        array('Nabız', 'saglik'),
        array('Ateş', 'saglik'),
        array('Kan şekeri', 'saglik'),
        array('Anemi', 'saglik'),
        array('Tiroid', 'saglik'),
        array('Kortizol', 'saglik'),
        array('Serotonin', 'saglik'),
        array('Dopamin', 'saglik'),
        array('Melatonin', 'saglik'),
        array('Uyku', 'saglik'),
        array('REM uykusu', 'saglik'),
        array('Biyolojik saat', 'saglik'),
        array('Obezite', 'saglik'),
        array('Sindirim', 'saglik'),
        array('Bağırsak', 'saglik'),
        array('Probiyotik', 'saglik'),
        array('Karaciğer', 'saglik'),
        array('Böbrek', 'saglik'),
        array('Akciğer', 'saglik'),
        array('Kalp', 'saglik'),
        array('Damar', 'saglik'),
        array('Solunum', 'saglik'),
        array('İnsülin', 'saglik'),
        array('Protein', 'saglik'),
        array('Karbonhidrat', 'saglik'),
        array('Kas', 'saglik'),
        array('Kemik', 'saglik'),
        array('Sinir sistemi', 'saglik'),
        array('Beyin', 'saglik'),
        
        // 🎓 Eğitim (331-370)
        array('Eğitim', 'egitim'),
        array('Öğrenme', 'egitim'),
        array('Okul', 'egitim'),
        array('Sınıf', 'egitim'),
        array('Ders', 'egitim'),
        array('Müfredat', 'egitim'),
        array('Öğrenci', 'egitim'),
        array('Öğretmen', 'egitim'),
        array('Karne', 'egitim'),
        array('Diploma', 'egitim'),
        array('Rehberlik', 'egitim'),
        array('Sınav', 'egitim'),
        array('Yazılı', 'egitim'),
        array('Sözlü', 'egitim'),
        array('Not sistemi', 'egitim'),
        array('Devamsızlık', 'egitim'),
        array('Başarı', 'egitim'),
        array('LGS', 'egitim'),
        array('YKS', 'egitim'),
        array('KPSS', 'egitim'),
        array('Ödev', 'egitim'),
        array('Proje', 'egitim'),
        array('Sunum', 'egitim'),
        array('Ders programı', 'egitim'),
        array('Mezuniyet', 'egitim'),
        array('Üniversite', 'egitim'),
        array('Fakülte', 'egitim'),
        array('Tez', 'egitim'),
        array('Staj', 'egitim'),
        array('Akademik danışman', 'egitim'),
        array('İntihal', 'egitim'),
        array('Kaynakça', 'egitim'),
        array('Makale', 'egitim'),
        array('Kütüphane', 'egitim'),
        array('Google Scholar', 'egitim'),
        array('YÖK', 'egitim'),
        array('ÖSYM', 'egitim'),
        
        // 🌐 Sosyal (371-400)
        array('DM', 'sosyal'),
        array('Story', 'sosyal'),
        array('Reels', 'sosyal'),
        array('Like', 'sosyal'),
        array('Yorum', 'sosyal'),
        array('Paylaşım', 'sosyal'),
        array('Trend', 'sosyal'),
        array('Keşfet', 'sosyal'),
        array('Takipçi', 'sosyal'),
        array('Engelleme', 'sosyal'),
        array('Ban', 'sosyal'),
        array('Profil', 'sosyal'),
        array('Etkileşim', 'sosyal'),
        array('Bildirim', 'sosyal'),
        array('Çevrim içi', 'sosyal'),
        array('Kullanıcı adı', 'sosyal'),
        array('Gizli hesap', 'sosyal'),
        array('Kültür', 'sosyal'),
        array('Gelenek', 'sosyal'),
        array('Ahlak', 'sosyal'),
        array('Etik', 'sosyal'),
        array('Prestij', 'sosyal'),
        array('İtibar', 'sosyal'),
        array('Güven', 'sosyal'),
        array('Önyargı', 'sosyal'),
        array('Ayrımcılık', 'sosyal'),
        array('Eşitlik', 'sosyal'),
        array('Adalet', 'sosyal'),
        array('Dayanışma', 'sosyal'),
        array('Liderlik', 'sosyal'),
        
        // 🧩 Genel (401-450)
        array('Sistem', 'genel'),
        array('Yapı', 'genel'),
        array('Model', 'genel'),
        array('Süreç', 'genel'),
        array('Döngü', 'genel'),
        array('Aşama', 'genel'),
        array('Denge', 'genel'),
        array('Kaos', 'genel'),
        array('Karmaşıklık', 'genel'),
        array('Basitlik', 'genel'),
        array('Netlik', 'genel'),
        array('Belirsizlik', 'genel'),
        array('Olasılık', 'genel'),
        array('Senaryo', 'genel'),
        array('Varsayım', 'genel'),
        array('Tahmin', 'genel'),
        array('Standart', 'genel'),
        array('Kalite', 'genel'),
        array('Performans', 'genel'),
        array('Verimlilik', 'genel'),
        array('Strateji', 'genel'),
        array('Taktik', 'genel'),
        array('Planlama', 'genel'),
        array('Organizasyon', 'genel'),
        array('Yönetim', 'genel'),
        array('Kapasite', 'genel'),
        array('Potansiyel', 'genel'),
        array('Sınır', 'genel'),
        array('Limit', 'genel'),
        array('Perspektif', 'genel'),
        array('Yaklaşım', 'genel'),
        array('İlke', 'genel'),
        array('Kural', 'genel'),
        array('Norm', 'genel'),
        array('Fonksiyon', 'genel'),
        array('Girdi', 'genel'),
        array('Çıktı', 'genel'),
        array('Sonuç', 'genel'),
        array('Etki', 'genel'),
        array('Geri bildirim', 'genel'),
        array('İyileştirme', 'genel'),
        array('Gelişim', 'genel'),
        array('Evrim', 'genel'),
        array('Adaptasyon', 'genel'),
        array('Sürdürülebilirlik', 'genel'),
        array('Tutarlılık', 'genel'),
        array('Bütünlük', 'genel'),
    );
}
