<?php
/**
 * Nedir.me - Part 3 Kavramlar (851-1000)
 */

if (!defined('ABSPATH')) exit;

function nedir_get_kavramlar_part3() {
    return array(
        // 🌐 Dijital Part 3 (851-920)
        array('Feed', 'dijital-teknoloji'),
        array('Akış', 'dijital-teknoloji'),
        array('Story süresi', 'dijital-teknoloji'),
        array('Keşfet algoritması', 'dijital-teknoloji'),
        array('Trend topic', 'dijital-teknoloji'),
        array('Retweet', 'dijital-teknoloji'),
        array('Repost', 'dijital-teknoloji'),
        array('Mention', 'dijital-teknoloji'),
        array('Tag', 'dijital-teknoloji'),
        array('Sabitleme', 'dijital-teknoloji'),
        array('Pin', 'dijital-teknoloji'),
        array('Draft', 'dijital-teknoloji'),
        array('Taslak', 'dijital-teknoloji'),
        array('Bildirim ayarları', 'dijital-teknoloji'),
        array('Engellenenler', 'dijital-teknoloji'),
        array('Topluluk kuralları', 'dijital-teknoloji'),
        array('Gizlilik ayarları', 'dijital-teknoloji'),
        array('İçerik filtresi', 'dijital-teknoloji'),
        array('İçerik politikası', 'dijital-teknoloji'),
        array('Telif hakkı', 'dijital-teknoloji'),
        array('DM isteği', 'dijital-teknoloji'),
        array('Hikâye yanıtı', 'dijital-teknoloji'),
        array('Close friends', 'dijital-teknoloji'),
        array('Arşiv', 'dijital-teknoloji'),
        array('Arama geçmişi', 'dijital-teknoloji'),
        array('Önbellek temizleme', 'dijital-teknoloji'),
        array('Veri silme', 'dijital-teknoloji'),
        array('Dijital detoks', 'dijital-teknoloji'),
        array('Hesap dondurma', 'dijital-teknoloji'),
        array('Hesap silme', 'dijital-teknoloji'),
        array('Kurtarma kodu', 'dijital-teknoloji'),
        array('Giriş denemesi', 'dijital-teknoloji'),
        array('Oturum süresi', 'dijital-teknoloji'),
        array('Hesap güvenliği', 'dijital-teknoloji'),
        array('Bot ağları', 'dijital-teknoloji'),
        array('Sahte etkileşim', 'dijital-teknoloji'),
        array('Shadow ban', 'dijital-teknoloji'),
        array('İçerik görünürlüğü', 'dijital-teknoloji'),
        array('Algoritmik ceza', 'dijital-teknoloji'),
        array('Mavi tik', 'dijital-teknoloji'),
        array('Etkileşim oranı', 'dijital-teknoloji'),
        array('Görüntülenme', 'dijital-teknoloji'),
        array('Tıklanma', 'dijital-teknoloji'),
        array('Gösterim', 'dijital-teknoloji'),
        array('Kaydetme', 'dijital-teknoloji'),
        array('İzlenme süresi', 'dijital-teknoloji'),
        array('Çıkma oranı', 'dijital-teknoloji'),
        array('Trafik kaynağı', 'dijital-teknoloji'),
        array('Organik trafik', 'dijital-teknoloji'),
        array('UTM kodu', 'dijital-teknoloji'),
        array('Dönüşüm', 'dijital-teknoloji'),
        array('Analitik panel', 'dijital-teknoloji'),
        array('Gerçek zamanlı veri', 'dijital-teknoloji'),
        array('Veri görselleştirme', 'dijital-teknoloji'),
        
        // 🧩 Genel Part 2 (921-1000)
        array('Çerçeve', 'genel'),
        array('Basamak', 'genel'),
        array('Risk algısı', 'genel'),
        array('Veri seti', 'genel'),
        array('Ölçüt', 'genel'),
        array('Kriter', 'genel'),
        array('Etkinlik', 'genel'),
        array('Optimizasyon', 'genel'),
        array('Liderlik tarzı', 'genel'),
        array('Karar mekanizması', 'genel'),
        array('Yetkinlik', 'genel'),
        array('Kapsam', 'genel'),
        array('Alan', 'genel'),
        array('Seviye', 'genel'),
        array('Derece', 'genel'),
        array('Ölçek', 'genel'),
        array('Hiyerarşi', 'genel'),
        array('Merkez', 'genel'),
        array('Çevre', 'genel'),
        array('Çekirdek', 'genel'),
        array('Katman', 'genel'),
        array('Boyut', 'genel'),
        array('Metodoloji', 'genel'),
        array('Ölçüm', 'genel'),
        array('Gösterge', 'genel'),
        array('Parametre', 'genel'),
        array('Değişken', 'genel'),
        array('Sabit', 'genel'),
        array('Uyum sağlama', 'genel'),
        array('Süreklilik', 'genel'),
        
        // Eksik kavramlar
        array('Eğitim', 'egitim'),
    );
}
